Repository nus-ncl/OctoBot, pull requests merged in 2022-07, with the labels that each got.

#36 [Octo-Bot/File-transfer] SSH activity in File Transfer Bot
  Octo-Bot/file-transfer-bot/ssh-bot/Dockerfile
  Octo-Bot/file-transfer-bot/ssh-bot/README
  Octo-Bot/file-transfer-bot/ssh-bot/id_rsa
  Octo-Bot/file-transfer-bot/ssh-bot/little_file
  Octo-Bot/file-transfer-bot/ssh-bot/ssh-concurrency.yaml
  Octo-Bot/file-transfer-bot/ssh-bot/start.py
Labels: enhancement

#58 [Octo-Bot] SSH Bot to create multiple SSH session and SCP Upload/Download
  .gitignore
  Octo-Bot/.DS_Store
  Octo-Bot/file-transfer-bot/.DS_Store
  Octo-Bot/file-transfer-bot/ssh-bot/Dockerfile
  Octo-Bot/file-transfer-bot/ssh-bot/README
  Octo-Bot/file-transfer-bot/ssh-bot/id_rsa
  Octo-Bot/file-transfer-bot/ssh-bot/ssh-concurrency.yaml
  Octo-Bot/file-transfer-bot/ssh-bot/start.py
  Octo-Bot/ssh-connection-bot/Dockerfile
  Octo-Bot/ssh-connection-bot/README.md
  Octo-Bot/ssh-connection-bot/bot/little_file
  Octo-Bot/ssh-connection-bot/bot/loop.sh
  Octo-Bot/ssh-connection-bot/bot/start.py
  Octo-Bot/ssh-connection-bot/play-example/ssh-concurrency.yaml
  Octo-Bot/ssh-connection-bot/play-example/ssh-download.yaml
  Octo-Bot/ssh-connection-bot/play-example/ssh-upload.yaml
  Octo-Play/ssh-concurrency.yaml
  Octo-Play/ssh-download.yaml
  Octo-Play/ssh-upload.yaml
Labels: enhancement

#56 [Octo-Bot/file-transfer-bot] bug fix (resolve issue #50)
  Octo-Bot/file-transfer-bot/bot/ftp_starter.py
Labels: bug, minor changes

#59 [Octo-Bot] Fix Web Browsing Bot Failed to get the URL to Crawl
  Octo-Bot/web-browsing-bot/util/scrapper.py
Labels: bug, octo-bot
